### ISSUE TITLE
[Epic] 예술품 등록 구현하기

### ISSUE THREAD

**Issue by Hongdonggeon** [JNU-econovation/CSRS#13]
- [x] 예술품 엔티티 클래스 생성하기 #17 
- [x] 예술품 등록 API 구현하기 #27 
- [ ] 예술품 등록 테스트 코드 작성하기
- [ ] 예술품 등록 중 필수 필드가 비어있을 경우 예외사항 처리하기
