### ISSUE TITLE
[Epic] 예술품 수정 구현하기

### ISSUE THREAD

**Issue by Hongdonggeon** [JNU-econovation/CSRS#24]
- [x] 예술품 수정 API 구현하기 #27 
- [ ] 예술품 수정 테스트 코드 작성하기
- [ ] 예술품 수정 입력 필수 필드가 비어있을 경우 예외사항 추가하기
