### ISSUE TITLE
[Epic] 예술품 삭제 구현하기

### ISSUE THREAD

**Issue by Hongdonggeon** [JNU-econovation/CSRS#25]
- [ ] (입찰중인 예술품) 삭제 안되게 예외사항 처리하기
- [x] (입찰이 시작 안한 예술품) 삭제 구현하기 #27 
- [ ] 예술품 삭제 테스트 코드 작성하기
