### ISSUE TITLE
[Epic] 예술품 입찰 구현하기

### ISSUE THREAD

**Issue by Hongdonggeon** [JNU-econovation/CSRS#30]
- [x] 예술품 입찰 기능 api 작성하기 #33 
- [ ] 예술품 입찰 기능 테스트 코드 작성하기
- [x] 입찰 최고 제시가격보다 낮거나 같은 가격을 제시할 시에 예외 발생하기
